### ISSUE TITLE
checklist for mympirun v4.0

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc-mympirun#105]
* [x] fix behaviour on partial nodes (cfr. #34, #93)
* [x] fix semantics of `--hybrid`, `--universe`, `--double` (cfr. #34, #41, #45, #93, #98, #104)
* [x] hang check for Intel MPI, fatal by default (cfr. #74, #88, #91)
* [x] better --output (cfr. #87, #90)
* [x] unit test suite (cfr. #85, #100)
* [x] add support for `--multi` (cfr. #101)
* [x] avoid dirname clashes in basepath (cfr. #95, #103)
* [x] end-to-end tests in vsc-testing (cfr. https://github.ugent.be/hpcugent/vsc-testing/tree/master/mympirun)
   * [x] incl. actual MPI hello test, cfr. https://github.ugent.be/hpcugent/vsc-testing/issues/33
* [x] automagically use local scheduler if `$PBS_NODEFILE` is not set (cfr. #106, fix in ~~#107~~ #109)
  * [x] see also https://github.ugent.be/hpcugent/vsc-testing/pull/30
* [x] use `pbsdsh` as default launcher for recent Intel MPI (instead of `ssh`) (cfr. #82, fix in ~~#110~~)
  * [x] make sure `pbsdsh` is always the default, cfr. #114
* [x] verify that mympingpong and HOD still work on top of new mympirun (AP @boegel): **OK!**
* [x] fix/improve (version) auto-detection of MPI class (#115)
* [x] fix IPL warning (cfr. ~~#117~~, fix in ~~#122~~)
* [x] updated documentation at vscentrum.be
  * example: https://www.vscentrum.be/cluster-doc/software/modules-lmod
  * use http://hpc.ugent.be/userwiki/index.php/User:VscMPIScripts as starting point (heavily outdated!)
  * host documentation in `vsc-mympirun` repo in `.rst` or `.md` format
  * see ~~#111~~
* [x] avoid use of `--setmpi` in tests (cfr. #116)
* [x] `mympirun` is not compatible with `OpenMPI` v2.0.x (cfr. ~~#113~~, "fixed" with #123)
* [x] evaluate `vsc-mympirun/.4.0.0-beta` hidden module with handful of HPC-UGent pilot users
   * done, feedback was positive, only issue that popped up was ~~#117~~
* [x] bump version to 4.0.0 + actual release
* [x]  --universe isn't balanced over available nodes (cfr. ~~#119~~, fixed with ~~120, #128~~)
* [x] OpenMPI doesn't allow oversubscribing (~~#96~~, fixed with ~~#125~~)
* [x] don't use default launcher for OpenMPI (~~#112~~)
* [x] stop using `-perhost`, use machinefile instead (~~#32~~, fixed with ~~#126~~)
* [x] don't hardcode sockets per node to 2 (~~#97~~, fixed with ~~#127, #129~~)

**Comment by stdweird** [comment]
looks very very good.
if there is something native to the selected MPI that supports torque, try to use that instead of `pbsssh`
