### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by wpoely86** [hpcugent/vsc-mympirun#49]
- [ ] Transfer to new vsc-install
- [ ] Write out/document the general workflow of mympirun.
- [ ] Write unit tests
- [ ] General code cleanup
- [ ] Document the main MPI classes
- [ ] Let user choose which schedule and MPI class to use
- [ ] Add links to all MPI documentation (per class)

**Comment by boegel** [comment]
also: fix known bugs (see open issues)?

**Comment by Iepoev** [comment]
everything except tests are included in #53 
the tests are present in the `tests` branch of the fork on my profile, I will submit a PR after #53 is finished and merged

**Comment by boegel** [comment]
@Caylo This is pretty much done, other than adding links to the MPI documentation for each different MPI library that is supported...
